name: Backlog Notify
on: push
jobs:
  backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Backlog Notify
        uses: atbay/workoutapp@master
        env:
          PROJECT_KEY: WOAP
          API_HOST: workoutapp.backlog.com
          API_KEY: ${{ secrets.BACK_LOG_API_KEY }}
